#!/usr/bin/env bash
# Kernel NFS server (privileged, host network, shared PID namespace). Exports /export read-only.
#
# Host-premounted mode: when the host has already mounted the kernel nfsd and
# rpc_pipefs pseudo-filesystems (requires sudo once), the container inherits
# them via the shared PID namespace and only registers the export table +
# starts the RPC services. Set NFS_HOST_PREMOUNTED=1 to enable.
set -euo pipefail

EXPORT_DIR="${EXPORT_DIR:-/export}"
CLIENTS="${NFS_CLIENTS:-*}"
NFS_OPTS="${NFS_OPTS:-ro,sync,no_subtree_check,no_root_squash,insecure,fsid=0}"

if [ "${NFS_HOST_PREMOUNTED:-0}" = "1" ]; then
    # Host already mounted /proc/fs/nfsd and an rpc_pipefs mount. Verify both
    # are visible (shared PID ns), then go straight to export registration.
    [ -d /proc/fs/nfsd/export ] || { echo "NFS_HOST_PREMOUNTED=1 but /proc/fs/nfsd/export missing on host" >&2; exit 1; }
    if ! mount | grep -q "rpc_pipefs"; then
        # last-resort: try to mount our own if host forgot the pipe dir
        mkdir -p /run/rpc_pipefs
        mountpoint -q /run/rpc_pipefs || mount -t rpc_pipefs rpc_pipefs /run/rpc_pipefs 2>/dev/null || true
    fi
else
    mkdir -p "$EXPORT_DIR" /var/lib/nfs/v4recovery /var/lib/nfs/rpc_pipefs /run/rpc_pipefs
    mountpoint -q /proc/fs/nfsd || mount -t nfsd nfsd /proc/fs/nfsd
    mountpoint -q /var/lib/nfs/rpc_pipefs || mount -t rpc_pipefs rpc_pipefs /var/lib/nfs/rpc_pipefs
    mountpoint -q /run/rpc_pipefs || mount -t rpc_pipefs rpc_pipefs /run/rpc_pipefs 2>/dev/null || true
fi

{
    echo "# generated by dsv41-exl3-nfs"
    IFS=',' read -ra addrs <<< "$CLIENTS"
    for addr in "${addrs[@]}"; do
        addr="${addr// /}"
        [[ -z "$addr" ]] && continue
        echo "$EXPORT_DIR ${addr}(${NFS_OPTS})"
    done
} > /etc/exports

exportfs -rav

rpcbind -w
rpc.statd --no-notify
rpc.nfsd 8
exec rpc.mountd --foreground --no-nfs-version 2 --no-nfs-version 3
