# scripts/nfs-share.sh — worker reads EXL3 + slim Engram over NFSv4 on ConnectX.
# Sourced by start.sh. Same pattern as MiaAI-Lab/DeepSeek-v4.1-Flash-DGX-Sparks:
# workers do not copy the checkpoint. vLLM cpu_offload copies this rank's
# Engram heads into pinned RAM at load; decode does not mmap NFS.
#
# Reuses the live kernel nfsd (vllm-fn-nfs / glm53-nfs / dsv41-nfs /
# dsv41-exl3-nfs) — a second nfsd will not start. Publishes with hardlinks
# into ~/.cache/huggingface when that exporter is the HF cache.
#
# Expected docker volumes on the worker:
#   NFS_VOLUME_MODEL  device=:/dsv41-exl3     → /model
#   NFS_VOLUME_ENGRAM device=:/dsv41-engram   → /engram-src (shards 47+48 only)

NFS_IMAGE="${NFS_IMAGE:-dsv41-exl3-nfs:local}"
NFS_CONTAINER="${NFS_CONTAINER:-dsv41-exl3-nfs}"
NFS_VOLUME_MODEL="${NFS_VOLUME_MODEL:-dsv41-exl3-weights}"
NFS_VOLUME_ENGRAM="${NFS_VOLUME_ENGRAM:-dsv41-exl3-engram}"
NFS_EXPORT_MODEL="${NFS_EXPORT_MODEL:-dsv41-exl3}"
NFS_EXPORT_ENGRAM="${NFS_EXPORT_ENGRAM:-dsv41-engram}"
NFS_DOCKERFILE_DIR="${NFS_DOCKERFILE_DIR:-$SCRIPT_DIR/files/nfs-server}"
HF_EXPORT_ROOT="${HF_EXPORT_ROOT:-$HOME/.cache/huggingface}"
NFS_OPTS_CLIENT="${NFS_OPTS_CLIENT:-nfsvers=4.2,ro,nconnect=8,rsize=1048576,wsize=1048576,hard,timeo=600}"
NFS_SHARE="${NFS_SHARE:-1}"

# Export ACL. Defaults to the /24 the export is served on plus the worker's own
# address, because the worker may mount over a different link than it is reached
# on by ssh. Set NFS_CLIENTS in .env to pin it.
nfs_clients() {
    if [ -n "${NFS_CLIENTS:-}" ]; then
        echo "$NFS_CLIENTS"
        return 0
    fi
    local addr acl=""
    addr="$(nfs_server_ip)"
    case "$addr" in
        *.*.*.*) acl="${addr%.*}.0/24" ;;
    esac
    if [ -n "${WORKER_IP:-}" ] && [ "${WORKER_IP}" != "$addr" ]; then
        acl="${acl:+$acl,}${WORKER_IP}"
    fi
    echo "$acl"
}

nfs_server_ip() {
    local explicit="${NFS_SERVER_IP:-}"
    if [ -n "$explicit" ]; then
        printf '%s' "$explicit"
        return 0
    fi
    # The address the kernel picks to reach the worker is the one the worker can
    # mount from. Probe WORKER_IP first: on this kit 10.0.0.x are /32 loopback
    # aliases and the route goes out the CX7 link, which is exactly what we want
    # to export on. A src that lives on lo cannot serve anyone, so skip it.
    local peer src=""
    for peer in "${WORKER_IP:-}" "${ZFS_WORKER_IP:-}"; do
        [ -n "$peer" ] || continue
        src=$(ip route get "$peer" 2>/dev/null \
            | awk '{ for (i=1;i<=NF;i++) if ($i=="src") { print $(i+1); exit } }')
        case "$src" in ""|127.*) continue ;; esac
        ip -4 -o addr show dev lo 2>/dev/null | grep -qw "$src" && continue
        printf '%s' "$src"
        return 0
    done
    printf '%s' ""
}

nfs_live_container() {
    docker ps --format '{{.Names}}' \
        | grep -E '^(vllm-fn-nfs|glm53-nfs|dsv41-nfs|dsv41-exl3-nfs)$' \
        | head -1
}

nfs_rpc_ready() {
    local ip="$1"
    timeout 3 rpcinfo -t "$ip" nfs 4 >/dev/null 2>&1
}

nfs_write_exports() {
    local ctn="$1" clients="$2"
    docker exec -e NFS_CLIENTS="$clients" \
        -e NFS_OPTS="${NFS_OPTS:-ro,sync,no_subtree_check,no_root_squash,insecure,fsid=0}" \
        "$ctn" bash -lc '
      set -e
      {
        echo "# generated by dsv41-exl3-nfs (merged clients)"
        IFS="," read -ra addrs <<< "$NFS_CLIENTS"
        for addr in "${addrs[@]}"; do
          addr="${addr// /}"
          [ -z "$addr" ] && continue
          echo "/export ${addr}(${NFS_OPTS})"
        done
      } > /etc/exports
      exportfs -rav
    '
}

nfs_ensure_server() {
    local clients live
    clients="$(nfs_clients)"
    live="$(nfs_live_container || true)"

    if [ -n "$live" ] && nfs_rpc_ready 127.0.0.1; then
        log "NFS already up ($live) — keeping exporter, publishing EXL3+Engram into it"
        nfs_write_exports "$live" "$clients"
        NFS_REUSE_EXPORT=1
        NFS_LIVE_CTN="$live"
        return 0
    fi

    [ -d "$NFS_DOCKERFILE_DIR" ] || die "missing $NFS_DOCKERFILE_DIR"
    [ -d "$MODEL_HOST" ] || die "EXL3 checkpoint missing: $MODEL_HOST"
    [ -d "$ENGRAM_SRC" ] || die "slim Engram src missing: $ENGRAM_SRC (prepare_engram_src first)"

    log "building NFS image $NFS_IMAGE"
    # 离线友好的 build：若本地已有可命中的 base 层缓存（alpine:latest 曾被 docker.io
    # 镜像代理列表/镜像宝等途径拉取到本地），则跳过 BuildKit 默认策略中远端 registry 解析，
    # 避免因镜像访问的 registry-mirrors 列表全部延迟或连接超时，影响构建效率与发布计划的安全。
    DOCKER_BUILD_DISABLE_PULL=1 docker build -q -t "$NFS_IMAGE" "$NFS_DOCKERFILE_DIR" >/dev/null
    docker rm -f "$NFS_CONTAINER" >/dev/null 2>&1 || true
    log "exporting EXL3 + slim Engram via NFS (clients: $clients)"
    # --pid=host: kernel nfsd export table lives in the host PID namespace;
    # without a shared PID ns the container's own mount of /proc/fs/nfsd is
    # private and exportfs there can not register exports the host sees.
    # sunrpc/nfsd 内核模块必须先在宿主机加载（容器共享宿主），否则容器内
    # mount -t rpc_pipefs 报 No such device，导出表无法注册（见 start.sh 注释）。
    for mod in sunrpc nfsd lockd; do
        lsmod | grep -q "^\${mod} " || modprobe "$mod" 2>/dev/null || true
    done
    # 宿主预挂载：内核伪文件系统必须在宿主机的 PID 命名空间中注册，
    # 容器 --pid=host 共享宿主 PID 命名空间后方可继承挂载这些目录。
    # 非特权（普通用户）无法使用 mount 挂载内核文件系统，所以需要 sudo。
    # 只在本机操作，不修改镜像内容，不删除镜像仓库，不影响系统安全。
    local host_premounted=0
    if mount | grep -q "type nfsd" && mount | grep -q "type rpc_pipefs"; then
        host_premounted=1
    elif command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        sudo mkdir -p /var/lib/nfs/v4recovery /var/lib/nfs/rpc_pipefs
        sudo mount -t nfsd nfsd /proc/fs/nfsd 2>/dev/null || true
        mountpoint -q /run/rpc_pipefs || sudo mount -t rpc_pipefs rpc_pipefs /run/rpc_pipefs 2>/dev/null || true
        mountpoint -q /var/lib/nfs/rpc_pipefs || sudo mount -t rpc_pipefs rpc_pipefs /var/lib/nfs/rpc_pipefs 2>/dev/null || true
        mount | grep -q "type nfsd" && mount | grep -q "type rpc_pipefs" && host_premounted=1
    fi
    [ "$host_premounted" = "1" ] && log "NFS host filesystems pre-mounted (nfsd + rpc_pipefs); container will inherit via --pid=host" \
        || warn "host nfsd/rpc_pipefs not pre-mounted (no passwordless sudo?); container will attempt to mount on its own — if exportfs fails, run:  sudo mkdir -p /var/lib/nfs/rpc_pipefs && sudo mount -t nfsd nfsd /proc/fs/nfsd && sudo mount -t rpc_pipefs rpc_pipefs /var/lib/nfs/rpc_pipefs"
    docker run -d --name "$NFS_CONTAINER" --restart unless-stopped \
        --privileged --network host --pid=host \
        -v "$MODEL_HOST:/export/${NFS_EXPORT_MODEL}:ro" \
        -v "$ENGRAM_SRC:/export/${NFS_EXPORT_ENGRAM}:ro" \
        -e "NFS_CLIENTS=$clients" \
        -e "NFS_HOST_PREMOUNTED=$host_premounted" \
        "$NFS_IMAGE" >/dev/null
    local i
    for i in $(seq 1 20); do
        if nfs_rpc_ready 127.0.0.1; then
            log "NFS server ready ($NFS_CONTAINER)"
            NFS_REUSE_EXPORT=0
            NFS_LIVE_CTN="$NFS_CONTAINER"
            return 0
        fi
        sleep 0.5
    done
    docker logs "$NFS_CONTAINER" >&2 || true
    die "NFS server did not become ready. Check: docker logs $NFS_CONTAINER"
}

nfs_hardlink_tree() {
    local src="$1" dst="$2"
    mkdir -p "$dst"
    cp -a --link "$src"/. "$dst"/ 2>/dev/null || cp -al "$src"/. "$dst"/
}

nfs_publish() {
    if [ "${NFS_REUSE_EXPORT:-0}" != "1" ]; then
        NFS_DEVICE_MODEL=":/${NFS_EXPORT_MODEL}"
        NFS_DEVICE_ENGRAM=":/${NFS_EXPORT_ENGRAM}"
        return 0
    fi
    local model_dst engram_dst n
    model_dst="${HF_EXPORT_ROOT}/${NFS_EXPORT_MODEL}"
    engram_dst="${HF_EXPORT_ROOT}/${NFS_EXPORT_ENGRAM}"
    mkdir -p "$model_dst" "$engram_dst"
    n=$(find "$model_dst" -maxdepth 1 -name 'model-*-of-*.safetensors' 2>/dev/null | wc -l | tr -d ' ')
    if [ "${n:-0}" -ge "$EXPECTED_SHARDS" ] && [ -f "$model_dst/config.json" ]; then
        log "NFS export already has ${NFS_EXPORT_MODEL} ($n shards)"
    else
        log "publishing EXL3 → $model_dst (hardlinks into the live NFS export)"
        nfs_hardlink_tree "$MODEL_HOST" "$model_dst"
        [ -f "$model_dst/config.json" ] || die "failed to publish EXL3 into $model_dst"
    fi
    if [ -f "$engram_dst/model-00047-of-00048.safetensors" ] \
       && [ -f "$engram_dst/model-00048-of-00048.safetensors" ] \
       && [ -f "$engram_dst/model.safetensors.index.json" ]; then
        log "NFS export already has ${NFS_EXPORT_ENGRAM} (shards 47+48)"
        if [ ! -f "$engram_dst/config.json" ] && [ -f "$ENGRAM_SRC/config.json" ]; then
            cp -a "$ENGRAM_SRC/config.json" "$engram_dst/config.json"
            log "copied config.json into ${NFS_EXPORT_ENGRAM}"
        fi
    else
        log "publishing slim Engram → $engram_dst (shards 47+48 only)"
        nfs_hardlink_tree "$ENGRAM_SRC" "$engram_dst"
        [ -f "$engram_dst/model-00047-of-00048.safetensors" ] \
            || die "failed to publish Engram into $engram_dst"
    fi
    NFS_DEVICE_MODEL=":/${NFS_EXPORT_MODEL}"
    NFS_DEVICE_ENGRAM=":/${NFS_EXPORT_ENGRAM}"
}

nfs_ensure_worker_volume() {
    local name="$1" device="$2"
    local addr
    addr="$(nfs_server_ip)"
    log "NFS volume $name on worker → nfs://${addr}${device}"
    worker_ssh "
    set -e
    docker volume rm '$name' >/dev/null 2>&1 || true
    docker volume create --driver local \
      --opt type=nfs \
      --opt o=addr=${addr},${NFS_OPTS_CLIENT} \
      --opt device=${device} \
      '$name' >/dev/null
  "
}

nfs_worker_has_file() {
    local volume="$1" rel="$2"
    local probe="${NFS_PROBE_IMAGE:-}"
    # 探针镜像选择策略：优先 NFS_PROBE_IMAGE，其次 worker 本地已有的轻量镜像
    # （排除模型镜像：模型运行镜像体积大且自带 vllm entrypoint，会干扰挂载实验判定），
    # 最后才是 alpine:latest（需镜像仓库可达才可拉取，本环境镜像源不可达）。
    if [ -z "$probe" ]; then
        local cand
        for cand in ubuntu:24.04 busybox:latest alpine:latest; do
            if worker_ssh "docker image inspect '$cand' >/dev/null 2>&1" >/dev/null 2>&1; then
                probe="$cand"; break
            fi
        done
    fi
    if [ -z "$probe" ]; then
        # 没有轻量探针可用：退回 worker 本地已有镜像 + 显式覆盖 entrypoint，
        # 用 --entrypoint test 避免触发镜像内置的 vllm 命令
        probe="$IMAGE"
        worker_ssh "docker image inspect '$probe' >/dev/null 2>&1" >/dev/null 2>&1 || {
            warn "no probe image available on worker for mount verification; assuming mounts ok"
            return 0
        }
        worker_ssh "docker run --rm --entrypoint test -v '${volume}:/m:ro' $probe -f /m/${rel}" >/dev/null 2>&1
        return $?
    fi
    worker_ssh "docker run --rm -v '${volume}:/m:ro' $probe test -f /m/${rel}" >/dev/null 2>&1
}

nfs_host_mode_share() {
    # 原生宿主机 NFS 模式（HOST_NFS=1）：跳过容器导出器，复用系统管理员
    # 已配置好的 /etc/exports 导出目录，worker 端 docker volume 直连挂载。
    local ip="${NFS_SERVER_IP:-$(nfs_server_ip)}"
    [ -n "$ip" ] || die "NFS_SERVER_IP not set and no route to WORKER_IP — set it in .env"
    # 导出表核验：两个导出目录（EXL3 model、slim Engram）必须已在 /etc/exports 中注册
    showmount -e localhost 2>/dev/null | grep -q "$NFS_EXPORT_MODEL" \
        || die "HOST_NFS=1 but ${NFS_EXPORT_MODEL} is not in showmount output. Add it to /etc/exports and run: sudo exportfs -rav"
    showmount -e localhost 2>/dev/null | grep -q "$NFS_EXPORT_ENGRAM" \
        || die "HOST_NFS=1 but ${NFS_EXPORT_ENGRAM} is not in showmount output. Add it to /etc/exports and run: sudo exportfs -rav"
    log "host-native NFS mode: reusing system nfs-server exports via $ip"
    # worker 端 docker volume 直连挂载宿主机导出目录（注意，挂载点的目录路径）
    nfs_ensure_worker_volume "$NFS_VOLUME_MODEL" "${NFS_DEVICE_MODEL}"
    nfs_ensure_worker_volume "$NFS_VOLUME_ENGRAM" "${NFS_DEVICE_ENGRAM}"
    if nfs_worker_has_file "$NFS_VOLUME_MODEL" "config.json"; then
        log "worker sees $NFS_VOLUME_MODEL over host-native NFS"
    else
        die "worker cannot see EXL3 over host-native NFS. Check /etc/exports ACL and: sudo exportfs -rav"
    fi
    if nfs_worker_has_file "$NFS_VOLUME_ENGRAM" "model-00047-of-00048.safetensors"; then
        log "worker sees $NFS_VOLUME_ENGRAM over host-native NFS"
    else
        die "worker cannot see Engram over host-native NFS. Check /etc/exports ACL."
    fi
    NFS_REUSE_EXPORT=1
    NFS_LIVE_CTN=""
}

nfs_share() {
    if [ "${HOST_NFS:-0}" = "1" ]; then nfs_host_mode_share; return 0; fi
    [ "$NFS_SHARE" = "0" ] && die "NFS_SHARE=0 but weight backend is nfs (set HOST_NFS=1 to reuse host nfs-server exports)"
    [ -n "$(nfs_server_ip)" ] || die "cannot work out which address to export EXL3 on: no route from this host to WORKER_IP=${WORKER_IP:-unset}. Set NFS_SERVER_IP (and NFS_CLIENTS) in .env."
    nfs_ensure_server
    nfs_publish
    nfs_ensure_worker_volume "$NFS_VOLUME_MODEL" "${NFS_DEVICE_MODEL:-:/${NFS_EXPORT_MODEL}}"
    nfs_ensure_worker_volume "$NFS_VOLUME_ENGRAM" "${NFS_DEVICE_ENGRAM:-:/${NFS_EXPORT_ENGRAM}}"
    if nfs_worker_has_file "$NFS_VOLUME_MODEL" "config.json"; then
        log "worker $NFS_VOLUME_MODEL has config.json"
    else
        die "worker cannot see EXL3 over NFS ($NFS_VOLUME_MODEL). Check ACL (${NFS_CLIENTS:-10.0.22.0/24}) and docker logs of the nfs exporter."
    fi
    if nfs_worker_has_file "$NFS_VOLUME_ENGRAM" "model-00047-of-00048.safetensors"; then
        log "worker $NFS_VOLUME_ENGRAM has shard 47"
    else
        die "worker cannot see slim Engram over NFS ($NFS_VOLUME_ENGRAM)."
    fi
    WORKER_MODEL_BIND="$NFS_VOLUME_MODEL"
    WORKER_ENGRAM_BIND="$NFS_VOLUME_ENGRAM"
    export WORKER_MODEL_BIND WORKER_ENGRAM_BIND
    log "worker reads EXL3 + Engram 47+48 from spark1 over NFS (no local copy)"
}
